/**
 * Deterministic keyword lists for search routing.
 * English + Arabic. Extend these arrays to tune behavior without changing rules.
 */

/** Live / external information — docs, news, prices, errors, releases. */
export const INTERNET_KEYWORDS = [
  // English
  "today",
  "latest",
  "news",
  "current",
  "currently",
  "documentation",
  "docs",
  "doc",
  "github",
  "price",
  "weather",
  "release",
  "released",
  "api",
  "npm",
  "error",
  "stack trace",
  "stackoverflow",
  "download",
  "install",
  "version",
  "changelog",
  "official",
  "website",
  "search online",
  "look up",
  "real-time",
  "real time",
  "now",
  "2024",
  "2025",
  "2026",
  // Arabic
  "اليوم",
  "آخر",
  "اخر",
  "أحدث",
  "احدث",
  "خبر",
  "أخبار",
  "اخبار",
  "الأخبار",
  "الاخبار",
  "السعر",
  "أسعار",
  "اسعار",
  "توثيق",
  "وثائق",
  "الوثائق",
  "جيت هب",
  "جيتهب",
  "github",
  "اصدار",
  "إصدار",
  "الاصدار",
  "الإصدار",
  "خطأ",
  "خطا",
  "الخطأ",
  "طقس",
  "الطقس",
  "الان",
  "الآن",
  "حاليا",
  "حالياً",
  "مباشر",
  "موقع",
  "الموقع الرسمي",
] as const;

/**
 * Past context — prior chats, projects, continuity.
 * Longer phrases are listed first so substring matching prefers specific hits.
 */
export const MEMORY_KEYWORDS = [
  // English (phrases first)
  "old conversation",
  "our project",
  "we discussed",
  "we talked",
  "you said",
  "i told you",
  "as i mentioned",
  "from before",
  "last time",
  "previous chat",
  "previous conversation",
  "earlier today",
  "remember when",
  "pick up where",
  "continue from",
  "remember",
  "previous",
  "earlier",
  "continue",
  "recall",
  "last chat",
  "my project",
  "our chat",
  "what did we",
  "you mentioned",
  // Arabic (phrases first)
  "المحادثة السابقة",
  "محادثة سابقة",
  "مشروعنا",
  "مشروعي",
  "كنا نتكلم",
  "كنا نتحدث",
  "قلت لي",
  "قلتلي",
  "ذكرت",
  "تذكر",
  "اذكر",
  "أذكر",
  "اكمل",
  "أكمل",
  "واصل",
  "واصِل",
  "قبل",
  "سابقا",
  "سابقاً",
  "المرة السابقة",
  "آخر مرة",
  "اخر مرة",
  "استمر",
  "تابع",
  "من قبل",
  "ما ذكرنا",
  "ما قلنا",
] as const;

/**
 * Explicitly needs BOTH stored context and fresh external data.
 */
export const MIXED_KEYWORDS = [
  // English
  "based on our",
  "from our conversation and",
  "what we discussed about the latest",
  "update on our project",
  "compare with what we said",
  "remember and check",
  "our previous research on",
  "continue researching",
  "latest on our",
  "current status of our",
  "news about our project",
  "docs for what we built",
  // Arabic
  "بناء على محادثتنا",
  "بناءً على محادثتنا",
  "ما ناقشناه وآخر",
  "ما ناقشناه واخر",
  "تحديث مشروعنا",
  "آخر أخبار مشروعنا",
  "اخر اخبار مشروعنا",
  "وثائق ما بنيناه",
  "تذكر وابحث",
  "اذكر وابحث",
  "اكمل البحث",
  "أكمل البحث",
  "واصل البحث",
  "قارن مع ما قلنا",
] as const;
